(part "TEN_50-2411WI"
    (packageRef "TEN502411WI")
    (interface
        (port "1" (symbPinId 1) (portName "+VIN_(VCC)") (portType INOUT))
        (port "2" (symbPinId 2) (portName "–VIN_(GND)") (portType INOUT))
        (port "3" (symbPinId 3) (portName "REMOTE_ON/OFF") (portType INOUT))
        (port "4" (symbPinId 4) (portName "+VOUT") (portType INOUT))
        (port "5" (symbPinId 5) (portName "–VOUT") (portType INOUT))
        (port "6" (symbPinId 6) (portName "TRIM") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "495-TEN50-2411WI")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/TRACO-Power/TEN-50-2411WI?qs=ckJk83FOD0X9tzvZCD0OJQ%3D%3D")
    (property "Manufacturer_Name" "Traco Power")
    (property "Manufacturer_Part_Number" "TEN 50-2411WI")
    (property "Description" "50 Watt DC/DC converter, industrial, 4:1 input, encapsulated, 2" x 1" metal package")
    (property "Datasheet_Link" "https://tracopower.com/ten50wi-datasheet/")
    (property "symbolName1" "TEN_50-2411WI")
)
